const DATABASE_NAME = '@gameplay';

const COLLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLLECTION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;

export { COLLLECTION_USERS, COLLLECTION_APPOINTMENTS };
